from Blackbox_Problems_fixed import problem_1, problem_2, problem_3
from grid_search import grid_search
from random_search import random_search
from pso import PSO
from ga import GA
import numpy as np
import random
import time

for seed in range(5):
    print('for seed = ', seed)
    print('')
    #grid search
    start_time = time.time()
    x,fitness = grid_search(problem_1,seed)
    print('problem 1 grid search result is:', fitness)
    print('and this result is for point: ', x)
    print('')
    x,fitness = grid_search(problem_2,seed)
    print('problem 2 grid search result is:', fitness)
    print('and this result is for point: ', x)
    print('')
    x,fitness = grid_search(problem_3,seed)
    print('problem 3 grid search result is:', fitness)
    print('and this result is for point: ', x)
    print('running time=',time.time() - start_time)
    print('')
    #random search
    start_time = time.time()
    x,fitness,iteration = random_search(problem_1,2,seed)
    print('problem 1 random search result is:', fitness)
    print('and this result is for point: ', x)
    print('iteration numbers = ', iteration)
    print('')
    x,fitness,iteration = random_search(problem_2,2,seed)
    print('problem 2 random search result is:', fitness)
    print('and this result is for point: ', x)
    print('iteration numbers = ', iteration)
    print('')
    x,fitness,iteration = random_search(problem_3,4,seed)
    print('problem 3 random search result is:', fitness)
    print('and this result is for point: ', x)
    print('iteration numbers = ', iteration)
    print('running time=',time.time() - start_time)
    print('')
    #PSO
    start_time = time.time()
    x,fitness,iteration = PSO(problem_1,2,seed)
    print('problem 1 PSO result is:', fitness)
    print('and this result is for point: ', x)
    print('iteration numbers = ', iteration)
    print('')
    x,fitness,iteration = PSO(problem_2,2,seed)
    print('problem 2 PSO result is:', fitness)
    print('and this result is for point: ', x)
    print('iteration numbers = ', iteration)
    print('')
    x,fitness,iteration = PSO(problem_3,4,seed)
    print('problem 3 PSO result is:', fitness)
    print('and this result is for point: ', x)
    print('iteration numbers = ', iteration)
    print('running time=',time.time() - start_time)
    print('')
    #GA
    start_time = time.time()
    x,fitness,iteration = GA(problem_1,2,seed)
    print('problem 1 GA result is:', fitness)
    print('and this result is for point: ', x)
    print('iteration numbers = ', iteration)
    print('')
    x,fitness,iteration = GA(problem_2,2,seed)
    print('problem 2 GA result is:', fitness)
    print('and this result is for point: ', x)
    print('iteration numbers = ', iteration)
    print('')
    x,fitness,iteration = GA(problem_3,4,seed)
    print('problem 3 GA result is:', fitness)
    print('and this result is for point: ', x)
    print('iteration numbers = ', iteration)
    print('running time=',time.time() - start_time)
    print('')